name: Think Imaginative
favicon: null
layout_spectrum: 0.6137085969094187
typography_spectrum: 0.258113841060549
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7554205465130508
  lightness: 0.23717644717544317
  saturation: 0.335303166648373
  rhythmicContrast: 0.46350476215593517
purpose: []
